### PR TITLE
fix: avoid directory switching when running fastlane

### LINKED ISSUE #2495: Improve Fastlane and Branch release without switching directories

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #2495

### CODE REVIEW

File: scripts/update-apk.sh [hunk 1]
```diff
@@ -60,18 +60,14 @@ for file in app*; do
 done
 
 if $IS_PUBLISH_BRANCH ;then
-    # Move to previous directory so that fastlane metadata gets uploaded
-    cd ..
     gem install fastlane
-    fastlane supply --aab ./apk/eventyay-attendee-master-app-playStore-release.aab --skip_upload_apk true --track alpha --json_key ./scripts/fastlane.json --package_name $PACKAGE_NAME $FASTLANE_DRY_RUN
+    fastlane supply --aab eventyay-attendee-master-app-playStore-release.aab --metadata_path ../fastlane/metadata/android --skip_upload_apk true --track alpha --json_key ../scripts/fastlane.json --package_name $PACKAGE_NAME $FASTLANE_DRY_RUN
```
Comment (iamareebjamal) [inline scripts/update-apk.sh]: Shouldn't it be `fastlane/metadata`?

Comment (adityastic) [reply scripts/update-apk.sh]: @iamareebjamal no, after testing it with my personal application I found that it looks for the folder which has en-US folder as its direct child.

Comment (adityastic) [reply scripts/update-apk.sh]: Here is a screenshot of a successful deployment. 
Screen Shot 2019-12-10 at 10 10 15 PM
