### PR TITLE
fix: Notification dot visibility logic

### LINKED ISSUE #2357: Notification dot's abrupt behaviour
**Describe the bug**
Notification red dot appears even when there is no new notification.

**To Reproduce**
1. Go to Events tab. You can observe the red dot now.
2. Open the notification section by clicking on the bell.
3. Go back to Events tab. Now the red dot is removed.
4. Go to another tab, let's say Search and go back to Events tab to refresh the content.
5. You can observe the red dot again. Now, there will be no new notifications even then dot is visible.

**Expected behavior**
Notification dot should not appear when there is no new notification.

**Smartphone Info:**
Device - Mi Note 5
Android Version - Oreo (8.1)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by tronku**
Fixes #2357 

Changes: In EventsFragment, the notification dot visibility was directly dependent on the logged-in status of the user and also on the observer in the StartupViewModel. So, I have removed the code responsible for setting the visibility based on logged-in status. Now, the dot only appears when there is a new notification.

Screenshots for the change:
ezgif-3-280153746787

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt [hunk 1]
```diff
@@ -143,8 +143,8 @@ class EventsFragment : Fragment(), BottomIconDoubleClick {
 
         rootView.notification.isVisible = eventsViewModel.isLoggedIn()
         rootView.notificationToolbar.isVisible = eventsViewModel.isLoggedIn()
-        rootView.newNotificationDot.isVisible = eventsViewModel.isLoggedIn()
-        rootView.newNotificationDotToolbar.isVisible = eventsViewModel.isLoggedIn()
+//        rootView.newNotificationDot.isVisible = eventsViewModel.isLoggedIn()
+//        rootView.newNotificationDotToolbar.isVisible = eventsViewModel.isLoggedIn()
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: revert this. 
How it can be a solution to the issue?

**Comment by liveHarshit** [comment]
Also follow https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ and https://twitter.com/iamareebjamal/status/1163190661396328448?s=20

File: app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt (hunk 1 above)
Comment (tronku) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: Okay, I will simply delete these lines instead of commenting them.

**Comment by tronku** [comment]
@liveHarshit okay I will follow the guidelines properly. I will remove the commented lines.

**Comment by tronku** [comment]
Removed all the unnecessary files
