### PR TITLE
fix: Make billing information compulsory for paid orders

### LINKED ISSUE #2134: Make billing info compulsory for paid orders

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #2134

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -691,7 +684,7 @@ class AttendeeFragment : Fragment(), ComplexBackPressFragment {
             rootView.email.checkEmpty()
 
         var checkBillingInfo = true
-        if (rootView.billingEnabledCheckbox.isChecked) {
+        if (safeArgs.amount > 0) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Invalid check. Please check if all tickets are free or donation. Because amount can be 0 due to application of discount code as well

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: So no billing info for donation tickets?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Sorry, there will be 2 checks, if all are free/donation and amount == 0, then no billing info

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Updated

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt [hunk 2]
```diff
@@ -220,15 +220,16 @@ class TicketsFragment : Fragment() {
...
         ticketsViewModel.mutableAmount.value = null
         findNavController(rootView).navigate(TicketsFragmentDirections.actionTicketsToAttendee(
             eventId = safeArgs.eventId,
             ticketIdAndQty = wrappedTicketAndQty,
             currency = safeArgs.currency,
-            amount = totalAmount
+            amount = totalAmount,
+            hasPaidTickets = ticketsViewModel.hasPaidTickets
         ))
+        ticketsViewModel.hasPaidTickets = false
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt]: Why?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt]: If we go back and change the ticket type, then it will remain true. Another solution is to set false in on create.
