### PR TITLE
fix: Resolve reset password mail UI issue

### LINKED ISSUE #2476: UI- Forgot-password_notification
1. When we press "I forgot my password" in login there is no pop-up notification regarding the password reset link sent to the respective email id.

To Reproduce the first bug;
1. Go to 'Profile'
2. Click on 'login'
3. Enter the registered email and continue
4. See error -->When you press "I forgot my password, it shows loading and no notification 
    appears regarding the reset link sent.

**Expected behavior**
We expect a notification saying that "A reset link has been sent to your respective e-mail"

**Screenshots**
Screenshot_bug1

**Smartphone Info:**
|Device         |Redmi Note-5 Pro|
|Android Version|Android-10|

**Would you like to work on the issue?**
- [No]

### PR DESCRIPTION
**Pull request by tronku**
Fixes #2476 

Changes:  Updated the message displayed to user in case of error. Removed the verifyMessage function.

Screenshots for the change:
WhatsApp Image 2019-12-11 at 12 41 46 AM

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 1]
```diff
@@ -88,20 +88,13 @@ class LoginViewModel(
             }.doFinally {
                 mutableProgress.value = false
             }.subscribe({
-                mutableRequestTokenSuccess.value = verifyMessage(it.message)
+                mutableRequestTokenSuccess.value = true
             }, {
-                mutableRequestTokenSuccess.value = verifyMessage(it.message.toString())
-                mutableError.value = resource.getString(R.string.email_not_in_server_message)
+                mutableRequestTokenSuccess.value = false
+                mutableError.value = resource.getString(R.string.reset_password_mail_message)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Show the message from server

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -313,6 +313,7 @@
     <string name="login_automatically_fail_message">Unable to log in automatically</string>
     <string name="login_fail_message">Unable to Login. Please check your credentials</string>
     <string name="email_not_in_server_message">Email address not present in server. Please check your email</string>
+    <string name="reset_password_mail_message">If your email was registered with us, you\'ll get an email with reset link shortly</string>
```
Comment (iamareebjamal) [inline app/src/main/res/values/strings.xml]: Remove

**Comment by iamareebjamal** [comment]
The UI should show the message from server

**Comment by tronku** [comment]
> The UI should show the message from server

Okay I will change it but the message should be changed from the server too. Otherwise, it will show "429 too many requests".

**Comment by iamareebjamal** [comment]
That case should be handled in the app as well. If the status code is 429, then show - "You've exhausted your attempts to send reset link, please try again after some time"

Nothing needs to be changed on server

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 3]
```diff
@@ -88,18 +89,22 @@ class LoginViewModel(
...
-        if (message == resource.getString(R.string.email_sent)) {
-            return true
+    private fun getErrorMessage(error: Throwable): String {
+        return if (error is HttpException) {
+            when (error.code()) {
+                429 -> resource.getString(R.string.reset_mail_limit_message).toString()
+                else -> error.message()
+            }
+        } else {
+            resource.getString(R.string.reset_password_mail_message).toString()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: This is not error message. This is what you get when it's a success

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Unexpected Error should be the error here - 'Oops, something went wrong'

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 4]
```diff
@@ -88,18 +89,22 @@ class LoginViewModel(
             }.doFinally {
                 mutableProgress.value = false
             }.subscribe({
-                mutableRequestTokenSuccess.value = verifyMessage(it.message)
+                mutableRequestTokenSuccess.value = true
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Message from the server should be shown here

Comment (tronku) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: No message is displayed in case of success. Only the mail sent layout is set to visible.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: The mail sent layout should display the message from server

Comment (tronku) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: What is the use of message from the server in case of success? Is there any scenario other than mail sent during success?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: So that if the server changes it's message, it is not needed to change the string in the app

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 5]
```diff
@@ -31,8 +33,8 @@ class LoginViewModel(
     val error: SingleLiveEvent<String> = mutableError
     private val mutableShowNoInternetDialog = MutableLiveData<Boolean>()
     val showNoInternetDialog: LiveData<Boolean> = mutableShowNoInternetDialog
-    private val mutableRequestTokenSuccess = MutableLiveData<Boolean>()
-    val requestTokenSuccess: LiveData<Boolean> = mutableRequestTokenSuccess
+    private val mutableRequestTokenSuccess = MutableLiveData<Pair<Boolean, String>>()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Don't use pair. Create a local data class or deconstruct into multiple livedata (not recommended)

Comment (tronku) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Okay

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 6]
```diff
@@ -31,15 +32,17 @@ class LoginViewModel(
...
+    private val mutableRequestTokenSuccess = MutableLiveData<RequestToken>()
+    val requestTokenSuccess: LiveData<RequestToken> = mutableRequestTokenSuccess
     private val mutableLoggedIn = SingleLiveEvent<Boolean>()
     var loggedIn: LiveData<Boolean> = mutableLoggedIn
     private val mutableValidPassword = MutableLiveData<Boolean>()
     val validPassword: LiveData<Boolean> = mutableValidPassword
 
     fun isLoggedIn() = authService.isLoggedIn()
 
+    data class RequestToken(val status: Boolean, val message: String)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]:
```suggestion
    data class LinkResetResponse(val status: Boolean, val message: String)
```

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 7]
```diff
@@ -88,18 +91,22 @@ class LoginViewModel(
...
-        if (message == resource.getString(R.string.email_sent)) {
-            return true
+    private fun getErrorMessage(error: Throwable): String {
+        return if (error is HttpException) {
+            when (error.code()) {
+                429 -> resource.getString(R.string.reset_mail_limit_message).toString()
+                else -> error.message()
+            }
+        } else {
+            resource.getString(R.string.something_went_wrong_message).toString()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: getString already returns String

Comment (tronku) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Nope, it returns String?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]: Then return String?

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 8]
```diff
@@ -88,18 +91,22 @@ class LoginViewModel(
             }.doFinally {
                 mutableProgress.value = false
             }.subscribe({
-                mutableRequestTokenSuccess.value = verifyMessage(it.message)
+                mutableRequestTokenSuccess.postValue(LinkResetResponse(true, it.message))
             }, {
-                mutableRequestTokenSuccess.value = verifyMessage(it.message.toString())
-                mutableError.value = resource.getString(R.string.email_not_in_server_message)
+                mutableRequestTokenSuccess.postValue(LinkResetResponse(false, getErrorMessage(it)))
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]:
```suggestion
                mutableRequestTokenSuccess.value =LinkResetResponse(false, getErrorMessage(it))
```

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt [hunk 9]
```diff
@@ -88,18 +91,22 @@ class LoginViewModel(
             }.doFinally {
                 mutableProgress.value = false
             }.subscribe({
-                mutableRequestTokenSuccess.value = verifyMessage(it.message)
+                mutableRequestTokenSuccess.postValue(LinkResetResponse(true, it.message))
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt]:
```suggestion
                mutableRequestTokenSuccess.value = LinkResetResponse(true, it.message)
```
