### PR TITLE
fix: Add prices in for all tickets in TicketIdAndQty

### LINKED ISSUE #2216: Add prices in for all tickets in TicketIdAndQtyWrapper
Currently, the donation ticket price is added others are 0.0

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by rob729**
Fixes #2216 

Changes: Removed unused/unnecessary variables from TicketsViewModel.

### CODE REVIEW

**Comment by rob729** [comment]
@liveHarshit Please review this PR and tell me whether this was the expected changes to be done to solve this issue so that I can proceed further.

**Comment by rob729** [comment]
> Travis build failed. Check for errors and indentation

**Comment by liveHarshit** [comment]
Provide GIF for the same, if possible. As it is an important check.

**Comment by rob729** [comment]
<a href="https://imgflip.com/gif/3fwldy"></a>

**Comment by rob729** [comment]
@liveHarshit The ticket type for both paid and free ticket is shown as paid in the app.
So should I do remove the TYPE_FREE code from TicketDetailsViewModel and write logic to set price text for free ticket in the TYPE_PAID block?

**Comment by liveHarshit** [comment]
> @liveHarshit The ticket type for both paid and free ticket is shown as paid in the app.
> So should I do remove the TYPE_FREE code from TicketDetailsViewModel and write logic to set price text for free ticket in the TYPE_PAID block?

Check the server response for free and paid tickets using chrome web tools with stetho.

**Comment by rob729** [comment]
<a href="https://imgflip.com/gif/3gf7dl"></a>
Please review the PR.

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt [hunk 1]
```diff
@@ -20,14 +20,15 @@ class TicketDetailsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView
                 itemView.price.text = resource.getString(R.string.donation)
                 itemView.subTotal.text = "$eventCurrency${"%.2f".format(donationAmount)}"
             }
-            TICKET_TYPE_FREE -> {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Why remove this?

Comment (rob729) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Because it was not being used.
For both free and paid tickets, TICKET_TYPE_PAID is used.
Do you want me to add the TICKET_TYPE_FREE back?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: They were being used, if free tickets are also of type PAID, then it is a bug in server

**Comment by rob729** [comment]
@iamareebjamal I have done the requested changes. Please review the PR.

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt (hunk 1 above)
Comment (rob729) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Ok

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt [hunk 2]
```diff
@@ -25,9 +25,14 @@ class TicketDetailsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView
                 itemView.subTotal.text = "${eventCurrency}0.00"
             }
             TICKET_TYPE_PAID -> {
-                itemView.price.text = "$eventCurrency${"%.2f".format(ticket.price)}"
-                val subTotal: Float? = ticket.price.times(ticketQuantity)
-                itemView.subTotal.text = "$eventCurrency${"%.2f".format(subTotal)}"
+                if (ticket.price == 0f) {
+                    itemView.price.text = resource.getString(R.string.free)
+                    itemView.subTotal.text = "${eventCurrency}0.00"
+                } else {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: This shouldn't be needed

Comment (rob729) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: So what should I do to solve this issue?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: > So what should I do to solve this issue?

Open an issue on the server-side to make ticket type free instead of rs 00 and let it be same.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Make sure if the ticket type is free from the server-side response, it should display Free instead of Rs 00 in the app also.

Comment (rob729) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Ok.
Thanks @liveHarshit .

**Comment by rob729** [comment]
@iamareebjamal The app is now working fine since the issue is solved on the server side.

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt [hunk 3]
```diff
@@ -2,10 +2,7 @@ package org.fossasia.openevent.general.ticket
 
 import android.view.View
 import androidx.recyclerview.widget.RecyclerView
-import kotlinx.android.synthetic.main.item_ticket_details.view.price
-import kotlinx.android.synthetic.main.item_ticket_details.view.qty
-import kotlinx.android.synthetic.main.item_ticket_details.view.subTotal
-import kotlinx.android.synthetic.main.item_ticket_details.view.ticketName
+import kotlinx.android.synthetic.main.item_ticket_details.view.*
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt]: Avoid wildcard imports

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt [hunk 4]
```diff
@@ -140,8 +140,12 @@ class TicketViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
 
     private fun setupDonationTicketPicker() {
         itemView.donationInput.addTextChangedListener(object : TextWatcher {
-            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) { /*Do Nothing*/ }
-            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) { /*Do Nothing*/ }
+            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) { /*Do Nothing*/
+            }
+
+            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) { /*Do Nothing*/
+            }
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt]: Why these changes?
