### PR TITLE
fix: Null check for ticket url 

### LINKED ISSUE #2228: App crashes on clicking tickets in event details
```
2019-08-03 23:19:01.716 27822-27822/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 27822
    java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:475)
        at android.net.Uri$StringUri.<init>(Uri.java)
        at android.net.Uri.parse(Uri.java:437)
        at org.fossasia.openevent.general.event.EventDetailsFragment$onCreateView$1.onClick(EventDetailsFragment.kt:139)
        at android.view.View.performClick(View.java:5647)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:941)
```

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #2228

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt [hunk 1]
```diff
@@ -136,11 +136,11 @@ class EventDetailsFragment : Fragment() {
 
         rootView.buttonTickets.setOnClickListener {
             val ticketUrl = currentEvent?.ticketUrl
-            if (Uri.parse(ticketUrl).host != getString(R.string.FRONTEND_HOST) &&
-                !ticketUrl.isNullOrEmpty()) {
-                Utils.openUrl(requireContext(), ticketUrl)
-            } else {
-                loadTicketFragment()
```
Comment (anhanh11001) [inline app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt]: I think you can just turn `  if (Uri.parse(ticketUrl).host != getString(R.string.FRONTEND_HOST) && !ticketUrl.isNullOrEmpty())` to `if (!ticketUrl.isNullOrEmpty() && Uri.parse(ticketUrl).host != getString(R.string.FRONTEND_HOST))`

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt]: > if (!ticketUrl.isNullOrEmpty() && Uri.parse(ticketUrl).host != getString(R.string.FRONTEND_HOST))

Oh, it's good if that works. Will check :+1:

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt]: Yes working. Updated :+1:
