### PR TITLE
fix: Display unauthorization error while loading events

### LINKED ISSUE #2109: Progress continues on unauthorization error
**Describe the bug**
Progress continues on authorization error while loading events,

```
E/EventsDataSource$createObservable: Fail on fetching page of events
    retrofit2.adapter.rxjava2.HttpException: HTTP 401 UNAUTHORIZED
```

**Would you like to work on the issue?**

yes

### LINKED ISSUE #2111: App crashes due to empty intent
**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #2109 
Fixes #2111

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt [hunk 1]
```diff
@@ -126,6 +127,10 @@ class EventsViewModel(
                     }
                 }
             }, {
+                if ((it as HttpException).code() == 401) {
```
Comment (ShridharGoel) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Define a constant

Comment (ShridharGoel) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Define constant in HttpErrors.kt

Comment (ShridharGoel) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Define constant in `HttpErrors.kt`.

Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: As said by codacy, this is an Unsafe cast. You can't know if the exception is HttpException, it can be IOException IllegalArgumentException, anything and you just casting it is waiting for a crash to happen.

Also, it's the developer's responsibility to handle any error except 500, where you can show Unfortunately, something went wrong, because you actually don't know what happened. 

All other errors must be handled. As a user, what am I supposed to do with a toast that says `HTTP 401 UNAUTHORIZED`?

I should either see `You must log in to see this {item}`, or if I am already logged in, then `Your session has expired, please login again`

And maybe being redirected to login screen

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: > I should either see `You must log in to see this {item}`, or if I am already logged in, then `Your session has expired, please login again`

I was not sure it is because of the user's login state. It shows when I try to change API and do not clear the app data. And events should load if the user is not logged in. I think it is due to the wrong Authorization which needs to re-request the Authenticator.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: > As said by codacy, this is an Unsafe cast. You can't know if the exception is HttpException, it can be IOException IllegalArgumentException, anything and you just casting it is waiting for a crash to happen.

Sorry about that.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: > I try to change API and do not clear the app data.

Then clear the data when API change happens

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Mean clear the app data programmatically?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Can we re-request the authenticator and reload events?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: No, because access token from one API won't work in another. This is very easily handled in Orga App. We simply show login screen anytime we encounter 401. Reason may be expired token or changing API base URL. Fixes every case

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Yes, It shows in case of login state only. For that error, we can log out the user and reload events. Because events should also load in not logged in state. :+1:

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Will fetch setting and test :+1:
Should I fetch setting at the starting of the app and store into the database or fetch every time when required?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Why fetching settings?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Sorry wrong PR.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Updated
